baseURL = "https://www.meltemodabas.net/"
languageCode = "en-us"
title = "Meltem Odabas"

[permalinks]
  works = "/works/:slug/"
  research = "/research/:slug/"

[pagination]
  pagerSize = 10

# allow raw HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
