baseURL = "https://www.meltemodabas.net/"
title = "Meltem Odabaş"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    languageCode = "en-us"
    languageName = "English"
    weight = 1
  [languages.tr]
    languageCode = "tr"
    languageName = "Türkçe"
    title = "Meltem Odabaş"
    weight = 2

[permalinks]
  works = "/works/:slug/"

[pagination]
  pagerSize = 10

# allow raw HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
